name: Descargar datos BCE

on:
  workflow_dispatch:  # para ejecutarlo manualmente

jobs:
  descargar_bce:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Instalar R
      uses: r-lib/actions/setup-r@v2

    - name: Instalar paquetes necesarios
      run: |
        Rscript -e "install.packages('rvest', repos='http://cran.us.r-project.org')"
        Rscript -e "install.packages('xml2', repos='http://cran.us.r-project.org')"

    - name: Ejecutar script R
      run: Rscript descargar_bce.R

    - name: Subir archivo al repositorio (opcional)
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add tasa_desempleo.csv
        git commit -m "Datos de desempleo actualizados automáticamente"
        git push
